### ISSUE TITLE
Tidak bisa menginput Jenis kelamin yang sesuai

### ISSUE THREAD

**Issue by akbarhlubis** [michaeledwardd/TubesPW_Perpustakaan#7]
Saat melakukan inputan terdapat 2 pilihan yaitu laki-laki dan perempuan, setelah dicoba satu persatu inputannya tetap sama di database yaitu 0. tidak ada 0 dan 1

**Comment by michaeledwardd** [comment]
oke nanti diperbaiki aja databasenya

**Comment by michaeledwardd** [comment]
berarti diubah aja gajadi pakai boolean tapi menggunakan varchar aja jadi kesannya kaya input prodi di register ugdnya modul 4

**Comment by akbarhlubis** [comment]
masalah ini sudah selesai dan fix menggunakan varchar
